version: '3.1'
services:

  php:
    # Builds PHP Apache image with the mysqli extension
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html


  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password


  # Web-interface for managing MySQL database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
