CREATE TABLE CUSTOMER (
	CustomerID			INT				NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FirstName			VARCHAR(30)		NOT NULL,
	LastName			VARCHAR(30)		NOT NULL,
	Phone				VARCHAR(12)		NULL,
	EmailAddress		VARCHAR(100)	NULL,
	Username			VARCHAR(25)		NOT NULL,
	Password			VARCHAR(300)	NOT NULL,
	AccountCreationDate	DATE			NOT NULL
);

CREATE TABLE EMPLOYEE (
	EmployeeID		INT				NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FirstName		VARCHAR(30)		NOT NULL,
	LastName		VARCHAR(30)		NOT NULL,
	EmailAddress	VARCHAR(100)	NULL,
	IsEmployeed		TINYINT			NOT NULL,
	Username		VARCHAR(25)		NOT NULL,
	Password		VARCHAR(300)	NOT NULL
);

CREATE TABLE VEHICLE (
	VehicleID		INT				NOT NULL AUTO_INCREMENT	PRIMARY KEY,
	VIN				VARCHAR(20)		NOT NULL,
	VehicleType		VARCHAR(30)		NOT NULL,
	VehicleModel	VARCHAR(50)		NOT NULL,
	Price			FLOAT			NOT NULL,
	Color			VARCHAR(10)		NOT NULL,
	IsSold			TINYINT			NOT NULL,
	ListingDate		DATE			NOT NULL,
	ImageName		Varchar(200)	NOT NULL,
	ListedBy		INT				NOT NULL,
	CONSTRAINT 		EMP_FK			FOREIGN KEY(ListedBy) REFERENCES EMPLOYEE(EmployeeID)
);

CREATE TABLE SALES (
	SaleID		INT				NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Date		DATE			NOT NULL,
	CustomerID	INT				NOT NULL,
	VehicleID	INT				NOT NULL,
	EmployeeID	INT				NOT NULL,
	CONSTRAINT	CUST_FK			FOREIGN KEY(CustomerID) REFERENCES CUSTOMER(CustomerID),
	CONSTRAINT	VEHICLE_FK		FOREIGN KEY(VehicleID)	REFERENCES VEHICLE(VehicleID),
	CONSTRAINT	EMPL_FK			FOREIGN KEY(EmployeeID) REFERENCES EMPLOYEE(EmployeeID)
);
